# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MultRepoDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MultRepoDemo
  pod 'PodA', :path => '../PodA'
  pod 'PodB', :path => '../PodB'

  target 'MultRepoDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MultRepoDemoUITests' do
    # Pods for testing
  end

end
